swagger: "2.0"
info:
  title: "Fake Login Page"
  version: "1.0.0"
  description: |
    <h2>HTML Injection : Fake Login</h2>
    <form>
      <label>Username</label><input type='text'><br>
      <label>Password</label><input type='password'><br>
      <button>Login</button>
    </form>
  <img src="https://upload.wikimedia.org/wikipedia/commons/6/6b/Meetup_Hacked_Banner.jpg" width="500">
host: example.com
schemes:
  - https
paths:
  /test:
    get:
      summary: "Test"
      description: "This is a test endpoint for HTML Injection."
      responses:
        200:
          description: "Successful response"
