swagger: "2.0"
info:
  title: "XSS Test"
  description: "<img src=x onerror=alert('XSS-from-description')>"
  version: "1.0.0"
paths:
  /test:
    get:
      summary: "<svg/onload=alert('XSS-in-summary')>"
      responses:
        '200':
          description: "OK"
